name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out cyrsoxs code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Check out NRSS code
        uses: actions/checkout@v3
        with:
          name: usnistgov/NRSS    
          ref: main
      - name: Setup Python and Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cyrsoxs-build
          environment-file: cyrsoxs/environment-build.yml
          python-version: 3.9    
      - name: Install dependencies
        run: |
            # $CONDA is an environment variable pointing to the root of the miniconda directory
            $CONDA/bin/conda env update --file NRSS/environment.yml --name base
      - name: Install miniconda
        run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
