name: Build wheels

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev libconfig++-dev nvidia-cuda-toolkit
          python -m pip install --upgrade pip
          pip install scikit-build-core pybind11 build

      - name: Build wheel
        run: python -m build --wheel

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.whl
